---
- name: 'Ensure Subscription Manager installed'
  ansible.builtin.dnf:
    name: 'subscription-manager'
    state: 'present'
    enablerepo: '*-baseos-rpms'  # To prevent issues with other repos that might not be working
  when: not rhsm_repair_config

- name: 'Ensure Subscription Manager configuration'
  ansible.builtin.template:
    src: 'rhsm.conf.j2'
    dest: '/etc/rhsm/rhsm.conf'
    mode: '0644'

- name: 'Check registration status with Foreman'
  ansible.builtin.command: '/usr/sbin/subscription-manager status'
  register: 'rhsm_status'
  failed_when: false
  changed_when: rhsm_status['rc'] != 0
  when: not rhsm_force_reregistration

- name: 'Register system'
  ansible.builtin.include_tasks:
    file: 'register_rhsm.yml'
  when: (rhsm_status['rc'] is defined and rhsm_status['rc'] != 0) or rhsm_force_reregistration

- name: 'Configure RHSM enabled repos'
  community.general.rhsm_repository:
    name: "{{ rhsm_enabled_repositories }}"
    state: 'enabled'
    purge: "{{ rhsm_purge_enabled_repositories }}"

- name: 'Purge other repo files'
  when: rhsm_purge_repo_files
  block:
    - name: 'Assemble list of allowed repo files'
      ansible.builtin.set_fact:
        rhsm_allowed_repos: "{{ ['/etc/yum.repos.d/redhat.repo'] + rhsm_allowed_repo_files | default([]) }}"

    - name: 'List repo files'
      ansible.builtin.find:
        path: '/etc/yum.repos.d'
        get_checksum: false
      register: 'repo_files'

    - name: 'Purge repo files'
      ansible.builtin.file:
        path: "{{ repo_file['path'] }}"
        state: 'absent'
      loop: "{{ repo_files['files'] }}"
      loop_control:
        loop_var: 'repo_file'
      when: repo_file['path'] not in rhsm_allowed_repos

- name: 'Ensure Katello host tools present'
  ansible.builtin.dnf:
    name:
      - 'katello-host-tools'
    state: 'present'
    update_cache: true
  when: rhsm_katello_host_tools_required

- name: 'Ensure Katello agent absent '
  ansible.builtin.dnf:
    name:
      - 'katello-agent'
    state: 'absent'

- name: 'Ensure Insights Client'
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - rhsm_insights_client_enabled | bool
  block:
    - name: 'Ensure insights-client package'
      ansible.builtin.package:
        name: 'insights-client'
        state: 'present'

    - name: 'Ensure insights-client confiuration'
      ansible.builtin.template:
        src: 'insights-client.conf.j2'
        dest: '/etc/insights-client/insights-client.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Get Red Hat Insights status'
      ansible.builtin.command: /usr/bin/insights-client --status
      register: 'insights_status'
      failed_when: false
      changed_when: insights_status['rc'] != 0

    - name: 'Register system with Red Hat Insights'
      ansible.builtin.command: /usr/bin/insights-client --register
      when: "'Insights API says this machine is NOT registered' in insights_status['stdout']"
      register: 'insights_registration'
      changed_when: "'Successfully registered host' in insights_registration['stdout']"
      failed_when: "'Successfully' not in insights_registration['stdout']"

    - name: 'Ensure insights-client.timer service'
      ansible.builtin.service:
        name: 'insights-client.timer'
        enabled: true
        state: 'started'
