---
- name: 'Ensure Subscription Manager installed'
  yum:
    name: 'subscription-manager'
    state: 'present'

- name: 'Check registration status with Foreman'
  shell: '/usr/sbin/subscription-manager status'
  register: 'rhsm_status'
  ignore_errors: true
  changed_when: rhsm_status.rc != 0
  when: not rhsm_force_reregistration

- name: 'Register system'
  include_tasks:
    file: 'register_rhsm.yml'
  when: (rhsm_status.rc is defined and rhsm_status.rc != 0) or rhsm_force_reregistration

- name: 'Purge other repo files'
  block:
    - name: 'Assemble list of allowed repo files'
      set_fact:
        rhsm_allowed_repos: "{{ ['/etc/yum.repos.d/redhat.repo'] + rhsm_allowed_repo_files | default([]) }}"
    - name: 'List repo files'
      find:
        path: '/etc/yum.repos.d'
        get_checksum: false
      register: 'repo_files'
    - name: 'Purge repo files'
      file:
        path: "{{ repo_file['path'] }}"
        state: 'absent'
      loop: "{{ repo_files['files'] }}"
      loop_control:
        loop_var: 'repo_file'
      when: repo_file['path'] not in rhsm_allowed_repos
  when: rhsm_purge_repo_files

- name: 'Ensure Katello host tools present '
  yum:
    name:
      - 'katello-host-tools'
    state: 'present'
    update_cache: true
  when: rhsm_server_type != 'cdn'

- name: 'Ensure Katello agent absent '
  yum:
    name:
      - 'katello-agent'
    state: 'absent'
  when: rhsm_server_type != 'cdn'
