---
- name: 'Ensure Subscription Manager installed'
  yum:
    name: 'subscription-manager'
    state: 'present'

- name: 'Check registration status with Foreman'
  shell: '/usr/sbin/subscription-manager status'
  register: 'rhsm_status'
  ignore_errors: true
  changed_when: rhsm_status.rc != 0
  when: not rhsm_force_reregistration

- name: 'Register system'
  include_tasks:
    file: 'register_rhsm.yml'
  when: (rhsm_status.rc is defined and rhsm_status.rc != 0) or rhsm_force_reregistration

- name: 'Install Katello agent'
  yum:
    name:
      - 'katello-host-tools'
    state: 'present'
    update_cache: true
