---
- name: 'Ensure Subscription Manager installed'
  ansible.builtin.yum:
    name: 'subscription-manager'
    state: 'present'

- name: 'Ensure Subscription Manager configuration'
  ansible.builtin.template:
    src: 'rhsm.conf.j2'
    dest: '/etc/rhsm/rhsm.conf'
    mode: 0600

- name: 'Check registration status with Foreman'
  ansible.builtin.command: '/usr/sbin/subscription-manager status'
  register: 'rhsm_status'
  ignore_errors: true
  changed_when: rhsm_status.rc != 0
  when: not rhsm_force_reregistration

- name: 'Register system'
  ansible.builtin.include_tasks:
    file: 'register_rhsm.yml'
  when: (rhsm_status.rc is defined and rhsm_status.rc != 0) or rhsm_force_reregistration

- name: 'Purge other repo files'
  block:
    - name: 'Assemble list of allowed repo files'
      ansible.builtin.set_fact:
        rhsm_allowed_repos: "{{ ['/etc/yum.repos.d/redhat.repo'] + rhsm_allowed_repo_files | default([]) }}"
    - name: 'List repo files'
      ansible.builtin.find:
        path: '/etc/yum.repos.d'
        get_checksum: false
      register: 'repo_files'
    - name: 'Purge repo files'
      ansible.builtin.file:
        path: "{{ repo_file['path'] }}"
        state: 'absent'
      loop: "{{ repo_files['files'] }}"
      loop_control:
        loop_var: 'repo_file'
      when: repo_file['path'] not in rhsm_allowed_repos
  when: rhsm_purge_repo_files

- name: 'Ensure Katello host tools present '
  ansible.builtin.yum:
    name:
      - 'katello-host-tools'
    state: 'present'
    update_cache: true
  when: rhsm_server_type != 'cdn'

- name: 'Ensure Katello agent absent '
  ansible.builtin.yum:
    name:
      - 'katello-agent'
    state: 'absent'
  when: rhsm_server_type != 'cdn'

- name: 'Ensure Insights Client'
  block:
    - name: 'Ensure insights-client package'
      ansible.builtin.package:
        name: 'insights-client'
        state: 'present'

    - name: 'Ensure insights-client confiuration'
      ansible.builtin.template:
        src: 'insights-client.conf.j2'
        dest: '/etc/insights-client/insights-client.conf'
        owner: 'root'
        group: 'root'
        mode: 0644

    - name: 'Register system with Red Hat Insights'
      ansible.builtin.command: /usr/bin/insights-client --register
      args:
        creates: '/etc/insights-client/.registered'
      register: 'insights_registration'
      changed_when: "'Successfully registered host' in insights_registration['stdout']"
      failed_when:
        - "'Successfully' not in insights_registration['stdout']"
        - "'skipped, since /etc/insights-client/.registered exists' not in insights_registration['stdout']"

    - name: 'Ensure insights-client.timer service'
      ansible.builtin.service:
        name: 'insights-client.timer'
        enabled: true
        state: 'started'
  when:
    - ansible_facts['distribution'] == 'RedHat'
    - rhsm_insights_client_enabled | bool
