---
- name: 'Remove old data'
  ansible.builtin.command: '/usr/sbin/subscription-manager clean'
  changed_when: true

- name: 'Ensure katello-ca-consumer absent'
  ansible.builtin.package:
    name: 'katello-ca-consumer-*'
    state: 'absent'
  when: rhsm_server_type != 'cdn'

- name: 'Generate new DMI system ID'
  when: rhsm_force_regenerate_dmi_uuid
  block:
    - name: 'Set facts'
      ansible.builtin.set_fact:
        dmi_uuid: "{{ lookup('pipe', '/usr/bin/uuidgen') }}"

    - name: 'Ensure katello.facts file'
      ansible.builtin.copy:
        dest: '/etc/rhsm/facts/katello.facts'
        content: |
          {"dmi.system.uuid": "{{ dmi_uuid }}", "virt.uuid": "{{ dmi_uuid }}"}
        owner: 'root'
        group: 'root'
        mode: '0644'

- name: 'Ensure no old repositories'
  ansible.builtin.file:
    path: '/etc/yum.repos.d'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: "{{ state }}"
  loop:
    - 'absent'
    - 'directory'
  loop_control:
    loop_var: 'state'

- name: 'Ensure katello-ca-consumer'
  ansible.builtin.yum:
    name: "http://{{ rhsm_foreman_server }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: 'present'
    disable_gpg_check: true
  when: rhsm_server_type != 'cdn'

- name: 'Register system'
  community.general.redhat_subscription:
    state: 'present'
    org_id: "{{ rhsm_organization }}"
    activationkey: "{{ rhsm_activation_key }}"
    server_hostname: "{{ rhsm_foreman_server }}"
    force_register: "{{ rhsm_force_register }}"
