---
- name: 'Ensure Subscription Manager configuration'
  template:
    src: 'rhsm.conf.j2'
    dest: '/etc/rhsm/rhsm.conf'
    mode: 0600

- name: 'Remove old data'
  command: '/usr/sbin/subscription-manager clean'

- name: 'Ensure no old repositories'
  file:
    path: '/etc/yum.repos.d'
    owner: 'root'
    group: 'root'
    mode: 0755
    state: "{{ state }}"
  loop:
    - 'absent'
    - 'directory'
  loop_control:
    loop_var: 'state'

- name: 'Ensure katello-ca-consumer'
  yum:
    name: "http://{{ rhsm_foreman_server }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: 'present'
  when: rhsm_server_type != 'cdn'

- name: 'Register systeem with Foreman'
  block:
    - name: 'Register system'
      redhat_subscription:
        state: 'present'
        org_id: "{{ rhsm_organization }}"
        activationkey: "{{ rhsm_activation_key }}"
        server_hostname: "{{ rhsm_foreman_server }}"
        auto_attach: "{{ rhsm_auto_attach }}"
        force_register: "{{ rhsm_force_register }}"
  rescue:
    - name: 'Attach subscriptions (fallback)'
      command: '/usr/sbin/subscription-manager attach --auto'
